### PR TITLE
async function should not return a Promise

### PR DESCRIPTION
**Pull request by alekitto**
Avoid to declare functions that already return a Promise (or not using `await`) as `async`

### CODE REVIEW

**Comment by mhart** [comment]
Not sure I understand why you want to change this?

**Comment by alekitto** [comment]
These functions already returns a Promise, it's useless to auto-wrap it with another Promise through the async function (that creates an implicit promise and then resolves it) when the first Promise could be returned synchronously

**Comment by mhart** [comment]
The functions are declared async to declare their intent, so that others know that they're awaitable – knowing whether to change them to async or not implies knowledge of the inner workings of the function, which breaks the encapsulation principle. It also means that if the inner details of the function change such that an await is required, then the function signature needs to change.

If v8 does indeed wrap an existing Promise with another Promise (are you sure about this?), then that's an easy optimization that they should improve in time.

If it's just a case of performance, then I'm not particularly inclined to change because the impact will be *very* low – if there's actually another issue, like a potential bug, then I'm happy to revisit this.

**Comment by mhart** [comment]
Hey @alekitto – I'm going to reopen this. It seems that the current state of the spec is that declaring a function async and returning a Promise *will* result in an extra tick, which is unfortunate (there is talk to change this though). It probably makes very little difference in performance to be honest – I imagine no more than 1ms per invocation – but we may as well try to minimize overhead as much as we can.

**Comment by mhart** [comment]
Got this in https://github.com/lambci/node-custom-lambda/commit/73feae28f8b99eca68ef80a88af070f4940c7369 – thanks for the contribution!

Have pushed this out in the latest layer versions

**Comment by alekitto** [comment]
Yes, promise optimization should land in node 12, but behind a flag
Thank you for your work!

**Pull request closed without merging**
