### PR TITLE
Change default major version.

### PR DESCRIPTION
**Pull request by dnalborczyk**

### CODE REVIEW

**Comment by mhart** [comment]
This is unnecessary. See:

https://github.com/lambci/node-custom-lambda/blob/master/v11.x/Dockerfile#L12-L13

**Comment by clayzermk1** [comment]
Permalink for the above Dockerfile link https://github.com/lambci/node-custom-lambda/blob/b1ce87ff08289803af4fd474b97bcd27c967b27f/v11.x/Dockerfile

@mhart Not to make a mountain out of a mole hill, but if it's unnecessary, wouldn't it be best to remove the `#ifndef` entirely? It looks like it's a failsafe in case the compiler argument isn't provided, in which case wouldn't this do bad things mixing node 10 with node >10? Wouldn't an error for `NODE_MAJOR` not being defined be preferable to some sort of mixed state? Or maybe replacing the `#define` for throwing an explicit error about requiring it from the command line.

Thank you for your time!

**Comment by mhart** [comment]
I did this back in https://github.com/lambci/node-custom-lambda/commit/a87751bebecb49aaf15c0af8c24d880a3948dd3f – the #define could be removed entirely, but then it's not as obvious, and also my linter complains about a bunch of other stuff because it's not defined 😄

**Comment by clayzermk1** [comment]
How about replacing the `#define` with an error then?

```c
#ifndef NODE_MAJOR
#error "NODE_MAJOR is not defined, please define it as a compiler argument."
#endif
```

**Comment by mhart** [comment]
Not sure what you mean? That's exactly what I did in that commit. https://github.com/lambci/node-custom-lambda/commit/a87751bebecb49aaf15c0af8c24d880a3948dd3f#diff-8f2ddd956427c3b358846d0d90564f8bR7

**Comment by clayzermk1** [comment]
Gah, my bad, I completely missed that. Thank you so much for taking the time to do that! Sorry for wasting your time! Cheers 🍻

**Pull request closed without merging**
